### ISSUE TITLE
Images not displaying 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-for-Vietnamese-Philosophy-Culture-and-Society#2]
@tu-chill can you help me figure out why the images are not displaying? They have been resized and are in the proper code..

**Comment by tu-chill** [comment]
@lidopaglia we can't seem to find where Jekyll is pushing these images too. Can you see if you can see them on the server?

**Comment by lidopaglia** [comment]
The folder containing the images in question is named `_media`.

Jekyll treats [folders prefixed with an underscore](https://jekyllrb.com/docs/structure/) differently during build. It will not copy the contents of the `_media` directory verbatim to the `_site` folder.

All you need to do is rename the folder to `media` and you should be good.

**Comment by CVE82** [comment]
@lidopaglia Thanks! Weird that didn't do it for the other media folders, appreciate the help!
