### ISSUE TITLE
Sorry One More Hero! 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-for-Vietnamese-Philosophy-Culture-and-Society#4]
I know this image is waaayy old and may not be perfect but any magic you could work would be fantastic! 

https://github.com/TULiberalArts/Center-for-Vietnamese-Philosophy-Culture-and-Society/blob/master/media/center_banner_1500.jpg

**Comment by ZMcGroarty** [comment]
![vietnamese-min](https://user-images.githubusercontent.com/15017242/44738617-7995b880-aac3-11e8-8a6b-12855bc5d689.png)
